// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHeMvgJIqdQt366zQAJG2iCL6A5DEmrF0',
    appId: '1:771078424485:web:dbf3c70d097e0f7e85ca4c',
    messagingSenderId: '771078424485',
    projectId: 'todoapp-b7a96',
    authDomain: 'todoapp-b7a96.firebaseapp.com',
    storageBucket: 'todoapp-b7a96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5G0YmR32Lh1png17ShKxDEddQT8LNDck',
    appId: '1:771078424485:android:0a722b7f7ae4e2b785ca4c',
    messagingSenderId: '771078424485',
    projectId: 'todoapp-b7a96',
    storageBucket: 'todoapp-b7a96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZKhJFsSk2HEAmAO0VHw81stOhKOpJOvo',
    appId: '1:771078424485:ios:0aa071d62b45901a85ca4c',
    messagingSenderId: '771078424485',
    projectId: 'todoapp-b7a96',
    storageBucket: 'todoapp-b7a96.firebasestorage.app',
    iosBundleId: 'com.newwave.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZKhJFsSk2HEAmAO0VHw81stOhKOpJOvo',
    appId: '1:771078424485:ios:baec2d55c86c99aa85ca4c',
    messagingSenderId: '771078424485',
    projectId: 'todoapp-b7a96',
    storageBucket: 'todoapp-b7a96.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHeMvgJIqdQt366zQAJG2iCL6A5DEmrF0',
    appId: '1:771078424485:web:ee81d9420967544285ca4c',
    messagingSenderId: '771078424485',
    projectId: 'todoapp-b7a96',
    authDomain: 'todoapp-b7a96.firebaseapp.com',
    storageBucket: 'todoapp-b7a96.firebasestorage.app',
  );

}