// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx4drsxOXI7RbeNG3BnlnmTsGf8PUkFxM',
    appId: '1:20636291172:web:e05c3f4bc16fdc7a068f71',
    messagingSenderId: '20636291172',
    projectId: 'todoapp-ec5e4',
    authDomain: 'todoapp-ec5e4.firebaseapp.com',
    storageBucket: 'todoapp-ec5e4.firebasestorage.app',
    measurementId: 'G-58TZC6L51S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyf4lHpvGtcCWPELFdsOwsFamXI27Q5XU',
    appId: '1:20636291172:android:447028f9bdf851c7068f71',
    messagingSenderId: '20636291172',
    projectId: 'todoapp-ec5e4',
    storageBucket: 'todoapp-ec5e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUzXfvbdQe2tbDBzxmorh8ZQIVp3fFAaQ',
    appId: '1:20636291172:ios:b9070f28fcd8f8a0068f71',
    messagingSenderId: '20636291172',
    projectId: 'todoapp-ec5e4',
    storageBucket: 'todoapp-ec5e4.firebasestorage.app',
    iosBundleId: 'com.newwave.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUzXfvbdQe2tbDBzxmorh8ZQIVp3fFAaQ',
    appId: '1:20636291172:ios:d59a89ba849e06fd068f71',
    messagingSenderId: '20636291172',
    projectId: 'todoapp-ec5e4',
    storageBucket: 'todoapp-ec5e4.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx4drsxOXI7RbeNG3BnlnmTsGf8PUkFxM',
    appId: '1:20636291172:web:e8e48490896c6a69068f71',
    messagingSenderId: '20636291172',
    projectId: 'todoapp-ec5e4',
    authDomain: 'todoapp-ec5e4.firebaseapp.com',
    storageBucket: 'todoapp-ec5e4.firebasestorage.app',
    measurementId: 'G-EC1MBXB4W8',
  );

}