# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :beta do
    # gradle(
    #     task: "clean"
    # )
    
    # gradle(
    #     task: "assemble",
    #     build_type: "Release"
    # )
    # Clean build folder
    sh "flutter clean"

    # Build the APK
    sh "flutter build apk --release"
  
    firebase_app_distribution(
        app: "1:771078424485:android:0a722b7f7ae4e2b785ca4c",
        firebase_cli_token: "1//0e1U7K1GN0SYFCgYIARAAGA4SNwF-L9IrGMNUHsXltgLhq17e0sl-QTQu4r8R_y5fpIMp3fuiausct6abPK_Vq5KQUEftiEwgYIA",
        apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
        groups: "testers"
    )
  end  
end