# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :beta do
    gradle(
        task: "clean"
    )
    
    gradle(
        task: "assemble",
        build_type: "Release"
        properties: {
      "android.injected.signing.store.file" => "./android/app/keystore.jks",
      "android.injected.signing.store.password" => ENV["STORE_PASSWORD"],
      "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
      "android.injected.signing.key.password" => ENV["KEY_PASSWORD"]
    }
    )
  
    firebase_app_distribution(
        app: "1:771078424485:android:0a722b7f7ae4e2b785ca4c",
        firebase_cli_token: "1//0ejfPX17ozDxQCgYIARAAGA4SNwF-L9IrfBX1z5R6yPxLhrWN0POo5LK5Zvv7MeABxr1HFhpiNsnWn5pMtuRQzkFuOCIPgoZFi6U",
        apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
        groups: "testers"
    )
  end  
end