name: Firebase Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      # Setup Fastlane
      - name: Setup Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Fastlane
        run: gem install fastlane

      # Decrypt google-services.json
      - name: Decrypt google-services.json
        run: |
          mkdir -p android/app
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json

      # Deploy to Firebase App Distribution
      - name: Deploy to Firebase App Distribution
        run: |
          cd android
          fastlane beta
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
